version: "3.9"
services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - ./chroma:/chroma
    environment:
      - ALLOW_RESET=true

  rag-app:
    build: ./
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    depends_on:
      - chromadb
